#!/command/with-contenv bash
#shellcheck shell=bash disable=SC2154,SC1091

"${s6wrap[@]}" echo "Started as an s6 service"
"${s6wrap[@]}" echo "Starting the php-fpm service..."

while true
do
    touch /tmp/php-fpm.up
    "${s6wrap[@]}" /usr/sbin/php-fpm8.2 -F
    rm -f /tmp/php-fpm.up
    "${s6wrap[@]}" echo "php-fpm Service has exited."
    sleep 10
    "${s6wrap[@]}" echo "Restarting php-fpm Service now..."
done
