#!/command/with-contenv bash
#shellcheck shell=bash disable=SC2154,SC1091

"${s6wrap[@]}" echo "Started as an s6 service"
"${s6wrap[@]}" echo "Starting the collectd service..."

while true
do
    touch /tmp/colletd.up
    "${s6wrap[@]}" /usr/sbin/collectd -f
    rm -f /tmp/collectd.up
    "${s6wrap[@]}" echo "collectd Service has exited."
    sleep 10
    "${s6wrap[@]}" echo "Restarting collectd Service now..."
done
